"""add quantity, status

Revision ID: 1067cc5aa0c2
Revises: 12c6a29e2ea8
Create Date: 2026-08-13 11:58:48.821040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1067cc5aa0c2'
down_revision: Union[str, Sequence[str], None] = '12c6a29e2ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('user_login', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('entity', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('request_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
                    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)

    op.add_column('assets', sa.Column('asset_status_id', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('quantity', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_assets_asset_status'), table_name='assets')
    op.create_foreign_key(None, 'assets', 'asset_status', ['asset_status_id'], ['id'])
    op.drop_column('assets', 'asset_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
