"""add serial_number for InventorizationItems

Revision ID: 32a90855374a
Revises: aa0f27f34fef
Create Date: 2026-08-19 16:42:18.410011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32a90855374a'
down_revision: Union[str, Sequence[str], None] = 'aa0f27f34fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventorization_items', sa.Column('serial_number', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_inventorization_items_serial_number'), 'inventorization_items', ['serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventorization_items_serial_number'), table_name='inventorization_items')
    op.drop_column('inventorization_items', 'serial_number')
    # ### end Alembic commands ###
