"""edit asset_model

Revision ID: 3c0df74d8536
Revises: cac6931f5425
Create Date: 2026-07-08 14:10:02.783262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0df74d8536'
down_revision: Union[str, Sequence[str], None] = 'cac6931f5425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_models', sa.Column('name', sa.String(length=150), nullable=False))
    op.alter_column('asset_models', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_asset_models_class_id'), table_name='asset_models')
    op.drop_index(op.f('ix_asset_models_model_name'), table_name='asset_models')
    op.create_index(op.f('ix_asset_models_asset_type_id'), 'asset_models', ['asset_type_id'], unique=False)
    op.create_index(op.f('ix_asset_models_name'), 'asset_models', ['name'], unique=False)
    op.drop_column('asset_models', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_models', sa.Column('model_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_asset_models_name'), table_name='asset_models')
    op.drop_index(op.f('ix_asset_models_asset_type_id'), table_name='asset_models')
    op.create_index(op.f('ix_asset_models_model_name'), 'asset_models', ['model_name'], unique=False)
    op.create_index(op.f('ix_asset_models_class_id'), 'asset_models', ['asset_type_id'], unique=False)
    op.alter_column('asset_models', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('asset_models', 'name')
    # ### end Alembic commands ###
