"""add_quantity_fields_to_inventorization_items

Revision ID: 4bd04094d764
Revises: 11feb8c10e95
Create Date: 2026-08-14 16:12:04.774435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bd04094d764'
down_revision: Union[str, Sequence[str], None] = '11feb8c10e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_write_offs', 'reason',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Причина',
               existing_nullable=False)
    op.alter_column('asset_write_offs', 'reason_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Описание причины',
               existing_nullable=True)
    op.alter_column('asset_write_offs', 'act_number',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Номер акта',
               existing_nullable=False)
    op.alter_column('asset_write_offs', 'act_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Дата акта',
               existing_nullable=False)
    op.alter_column('asset_write_offs', 'disposal_method',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Метод утилизации',
               existing_nullable=True)
    op.alter_column('asset_write_offs', 'initiated_by',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Инициатор',
               existing_nullable=False)
    op.alter_column('asset_write_offs', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Примечания',
               existing_nullable=True)
    op.add_column('inventorization_items', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('inventorization_items', sa.Column('quantity_fact', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventorization_items', 'quantity_fact')
    op.drop_column('inventorization_items', 'quantity')
    op.alter_column('asset_write_offs', 'notes',
               existing_type=sa.TEXT(),
               comment='Примечания',
               existing_nullable=True)
    op.alter_column('asset_write_offs', 'initiated_by',
               existing_type=sa.VARCHAR(length=20),
               comment='Инициатор',
               existing_nullable=False)
    op.alter_column('asset_write_offs', 'disposal_method',
               existing_type=sa.VARCHAR(length=50),
               comment='Метод утилизации',
               existing_nullable=True)
    op.alter_column('asset_write_offs', 'act_date',
               existing_type=sa.DATE(),
               comment='Дата акта',
               existing_nullable=False)
    op.alter_column('asset_write_offs', 'act_number',
               existing_type=sa.VARCHAR(length=100),
               comment='Номер акта',
               existing_nullable=False)
    op.alter_column('asset_write_offs', 'reason_description',
               existing_type=sa.TEXT(),
               comment='Описание причины',
               existing_nullable=True)
    op.alter_column('asset_write_offs', 'reason',
               existing_type=sa.VARCHAR(length=50),
               comment='Причина',
               existing_nullable=False)
    # ### end Alembic commands ###
