"""initial state

Revision ID: 4c537c81d184
Revises: 
Create Date: 2026-07-06 17:11:02.727237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c537c81d184'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_company_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_location_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_pc_data_id'), table_name='pc_data')
    op.drop_index(op.f('ix_pc_data_username'), table_name='pc_data')
    op.drop_table('pc_data')
    op.drop_index(op.f('ix_vendors_company_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_supplier_number'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_vendor_class_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_vendor_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_android_data_id'), table_name='android_data')
    op.drop_index(op.f('ix_android_data_serial_number'), table_name='android_data')
    op.drop_table('android_data')
    op.drop_index(op.f('ix_vendor_classes_class_id'), table_name='vendor_classes')
    op.drop_index(op.f('ix_vendor_classes_name'), table_name='vendor_classes')
    op.drop_table('vendor_classes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_classes',
    sa.Column('class_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['zup_employees.employee_id'], name=op.f('vendor_classes_created_by_fkey')),
    sa.PrimaryKeyConstraint('class_id', name=op.f('vendor_classes_pkey'))
    )
    op.create_index(op.f('ix_vendor_classes_name'), 'vendor_classes', ['name'], unique=True)
    op.create_index(op.f('ix_vendor_classes_class_id'), 'vendor_classes', ['class_id'], unique=False)
    op.create_table('android_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('request_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('device', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('system', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('hardware', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('network', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('battery', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('android_data_pkey'))
    )
    op.create_index(op.f('ix_android_data_serial_number'), 'android_data', ['serial_number'], unique=True)
    op.create_index(op.f('ix_android_data_id'), 'android_data', ['id'], unique=False)
    op.create_table('vendors',
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('supplier_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vendor_class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('vendors_company_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['zup_employees.employee_id'], name=op.f('vendors_created_by_fkey')),
    sa.ForeignKeyConstraint(['vendor_class_id'], ['vendor_classes.class_id'], name=op.f('vendors_vendor_class_id_fkey')),
    sa.PrimaryKeyConstraint('vendor_id', name=op.f('vendors_pkey'))
    )
    op.create_index(op.f('ix_vendors_vendor_id'), 'vendors', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_vendors_vendor_class_id'), 'vendors', ['vendor_class_id'], unique=False)
    op.create_index(op.f('ix_vendors_supplier_number'), 'vendors', ['supplier_number'], unique=True)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_index(op.f('ix_vendors_company_id'), 'vendors', ['company_id'], unique=False)
    op.create_table('pc_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('network', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('os', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('office_package', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('programs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pc_data_pkey'))
    )
    op.create_index(op.f('ix_pc_data_username'), 'pc_data', ['username'], unique=True)
    op.create_index(op.f('ix_pc_data_id'), 'pc_data', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('company_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('gen_director', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['zup_employees.employee_id'], name=op.f('companies_created_by_fkey')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], name=op.f('companies_location_id_fkey')),
    sa.PrimaryKeyConstraint('company_id', name=op.f('companies_pkey'))
    )
    op.create_index(op.f('ix_companies_location_id'), 'companies', ['location_id'], unique=False)
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    op.create_index(op.f('ix_companies_company_id'), 'companies', ['company_id'], unique=False)
    # ### end Alembic commands ###
