"""Initial migration

Revision ID: 53bc860dca5f
Revises: 
Create Date: 2026-04-16 12:39:31.712865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53bc860dca5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('floor', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_locations_city'), 'locations', ['city'], unique=False)
    op.create_index(op.f('ix_locations_country'), 'locations', ['country'], unique=False)
    op.create_index(op.f('ix_locations_location_id'), 'locations', ['location_id'], unique=False)
    op.create_table('vendor_classes',
    sa.Column('vendor_class_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('vendor_class_id')
    )
    op.create_index(op.f('ix_vendor_classes_name'), 'vendor_classes', ['name'], unique=True)
    op.create_index(op.f('ix_vendor_classes_vendor_class_id'), 'vendor_classes', ['vendor_class_id'], unique=False)
    op.create_table('asset_classes',
    sa.Column('class_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('class_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_type_id'], ['asset_types.asset_type_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_asset_classes_class_id'), 'asset_classes', ['class_id'], unique=False)
    op.create_index(op.f('ix_asset_classes_class_name'), 'asset_classes', ['class_name'], unique=False)
    op.create_index(op.f('ix_asset_classes_class_type_id'), 'asset_classes', ['class_type_id'], unique=False)
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('gen_director', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_companies_company_id'), 'companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    op.create_index(op.f('ix_companies_location_id'), 'companies', ['location_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('warehouse_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('prepared_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['prepared_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('warehouse_id')
    )
    op.create_index(op.f('ix_warehouses_location_id'), 'warehouses', ['location_id'], unique=False)
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=True)
    op.create_index(op.f('ix_warehouses_prepared_by'), 'warehouses', ['prepared_by'], unique=False)
    op.create_index(op.f('ix_warehouses_warehouse_id'), 'warehouses', ['warehouse_id'], unique=False)
    op.create_table('asset_models',
    sa.Column('model_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_serial_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['asset_classes.class_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_index(op.f('ix_asset_models_class_id'), 'asset_models', ['class_id'], unique=False)
    op.create_index(op.f('ix_asset_models_is_active'), 'asset_models', ['is_active'], unique=False)
    op.create_index(op.f('ix_asset_models_model_id'), 'asset_models', ['model_id'], unique=False)
    op.create_index(op.f('ix_asset_models_model_name'), 'asset_models', ['model_name'], unique=False)
    op.create_table('vendors',
    sa.Column('vendor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor_class_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['vendor_class_id'], ['vendor_classes.vendor_class_id'], ),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    op.create_index(op.f('ix_vendors_company_id'), 'vendors', ['company_id'], unique=False)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_index(op.f('ix_vendors_vendor_class_id'), 'vendors', ['vendor_class_id'], unique=False)
    op.create_index(op.f('ix_vendors_vendor_id'), 'vendors', ['vendor_id'], unique=False)
    op.create_table('asset_catalog',
    sa.Column('catalog_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('warranty_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['asset_classes.class_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['asset_models.model_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('catalog_id')
    )
    op.create_index(op.f('ix_asset_catalog_asset_id'), 'asset_catalog', ['asset_id'], unique=True)
    op.create_index(op.f('ix_asset_catalog_catalog_id'), 'asset_catalog', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_asset_catalog_class_id'), 'asset_catalog', ['class_id'], unique=False)
    op.create_index(op.f('ix_asset_catalog_model_id'), 'asset_catalog', ['model_id'], unique=False)
    op.create_index(op.f('ix_asset_catalog_owner_id'), 'asset_catalog', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_user_assets_asset_id'), table_name='user_assets')
    op.drop_index(op.f('ix_user_assets_returned_at'), table_name='user_assets')
    op.drop_index(op.f('ix_user_assets_user_id'), table_name='user_assets')
    op.drop_table('user_assets')
    op.drop_index(op.f('ix_asset_types_type_id'), table_name='asset_types')
    op.create_index(op.f('ix_asset_types_name'), 'asset_types', ['name'], unique=True)
    op.drop_column('asset_types', 'type_id')
    op.add_column('assets', sa.Column('asset_type_id', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('manufacturer_id', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.alter_column('assets', 'asset_status',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('assets', 'inventory_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('assets', 'serial_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('assets', 'prepared_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('assets', 'checked_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_assets_type_id'), table_name='assets')
    op.create_index(op.f('ix_assets_asset_type_id'), 'assets', ['asset_type_id'], unique=False)
    op.create_index(op.f('ix_assets_location_id'), 'assets', ['location_id'], unique=False)
    op.create_index(op.f('ix_assets_manufacturer_id'), 'assets', ['manufacturer_id'], unique=False)
    op.create_index(op.f('ix_assets_price'), 'assets', ['price'], unique=False)
    op.create_index(op.f('ix_assets_vendor_id'), 'assets', ['vendor_id'], unique=False)
    op.drop_constraint(op.f('assets_type_id_fkey'), 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'vendors', ['manufacturer_id'], ['vendor_id'])
    op.create_foreign_key(None, 'assets', 'users', ['prepared_by'], ['user_id'])
    op.create_foreign_key(None, 'assets', 'asset_types', ['asset_type_id'], ['asset_type_id'])
    op.create_foreign_key(None, 'assets', 'locations', ['location_id'], ['location_id'])
    op.create_foreign_key(None, 'assets', 'vendors', ['vendor_id'], ['vendor_id'])
    op.create_foreign_key(None, 'assets', 'users', ['checked_by'], ['user_id'])
    op.drop_column('assets', 'source')
    op.drop_column('assets', 'type_id')
    op.drop_column('assets', 'location')
    op.alter_column('software', 'admin_permission',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('software', 'who_installed',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'software', 'users', ['who_installed'], ['user_id'])
    op.add_column('users', sa.Column('role', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'software', type_='foreignkey')
    op.alter_column('software', 'who_installed',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('software', 'admin_permission',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('assets', sa.Column('location', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key(op.f('assets_type_id_fkey'), 'assets', 'asset_types', ['type_id'], ['type_id'])
    op.drop_index(op.f('ix_assets_vendor_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_price'), table_name='assets')
    op.drop_index(op.f('ix_assets_manufacturer_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_location_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type_id'), table_name='assets')
    op.create_index(op.f('ix_assets_type_id'), 'assets', ['type_id'], unique=False)
    op.alter_column('assets', 'checked_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('assets', 'prepared_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('assets', 'serial_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('assets', 'inventory_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('assets', 'asset_status',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('assets', 'vendor_id')
    op.drop_column('assets', 'manufacturer_id')
    op.drop_column('assets', 'price')
    op.drop_column('assets', 'location_id')
    op.drop_column('assets', 'asset_type_id')
    op.add_column('asset_types', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_asset_types_name'), table_name='asset_types')
    op.create_index(op.f('ix_asset_types_type_id'), 'asset_types', ['type_id'], unique=True)
    op.create_table('user_assets',
    sa.Column('assign_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('returned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], name=op.f('user_assets_asset_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('user_assets_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assign_id', name=op.f('user_assets_pkey'))
    )
    op.create_index(op.f('ix_user_assets_user_id'), 'user_assets', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_assets_returned_at'), 'user_assets', ['returned_at'], unique=False)
    op.create_index(op.f('ix_user_assets_asset_id'), 'user_assets', ['asset_id'], unique=False)
    op.drop_index(op.f('ix_asset_catalog_owner_id'), table_name='asset_catalog')
    op.drop_index(op.f('ix_asset_catalog_model_id'), table_name='asset_catalog')
    op.drop_index(op.f('ix_asset_catalog_class_id'), table_name='asset_catalog')
    op.drop_index(op.f('ix_asset_catalog_catalog_id'), table_name='asset_catalog')
    op.drop_index(op.f('ix_asset_catalog_asset_id'), table_name='asset_catalog')
    op.drop_table('asset_catalog')
    op.drop_index(op.f('ix_vendors_vendor_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_vendor_class_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_company_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_asset_models_model_name'), table_name='asset_models')
    op.drop_index(op.f('ix_asset_models_model_id'), table_name='asset_models')
    op.drop_index(op.f('ix_asset_models_is_active'), table_name='asset_models')
    op.drop_index(op.f('ix_asset_models_class_id'), table_name='asset_models')
    op.drop_table('asset_models')
    op.drop_index(op.f('ix_warehouses_warehouse_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_prepared_by'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_location_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_companies_location_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_asset_classes_class_type_id'), table_name='asset_classes')
    op.drop_index(op.f('ix_asset_classes_class_name'), table_name='asset_classes')
    op.drop_index(op.f('ix_asset_classes_class_id'), table_name='asset_classes')
    op.drop_table('asset_classes')
    op.drop_index(op.f('ix_vendor_classes_vendor_class_id'), table_name='vendor_classes')
    op.drop_index(op.f('ix_vendor_classes_name'), table_name='vendor_classes')
    op.drop_table('vendor_classes')
    op.drop_index(op.f('ix_locations_location_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_country'), table_name='locations')
    op.drop_index(op.f('ix_locations_city'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
