"""change model Position

Revision ID: 633cb5ea4be7
Revises: 71abeb84ca81
Create Date: 2026-07-07 12:16:41.997223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633cb5ea4be7'
down_revision: Union[str, Sequence[str], None] = '71abeb84ca81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zup_positions', 'creation_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('zup_positions', 'expiration_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zup_positions', 'expiration_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('zup_positions', 'creation_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
