"""last current work revision

Revision ID: 6978eb1ebb86
Revises: 796e4d0ffced
Create Date: 2026-07-23 11:11:29.396330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6978eb1ebb86'
down_revision: Union[str, Sequence[str], None] = '796e4d0ffced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workshops_code'), table_name='workshops')
    op.drop_index(op.f('ix_workshops_is_active'), table_name='workshops')
    op.drop_index(op.f('ix_workshops_name'), table_name='workshops')
    op.drop_index(op.f('ix_workshops_workshop_id'), table_name='workshops')
    op.drop_table('workshops')
    op.drop_index(op.f('ix_asset_positions_asset_id'), table_name='asset_positions')
    op.drop_index(op.f('ix_asset_positions_id'), table_name='asset_positions')
    op.drop_index(op.f('ix_asset_positions_is_active'), table_name='asset_positions')
    op.drop_index(op.f('ix_asset_positions_workshop_id'), table_name='asset_positions')
    op.drop_table('asset_positions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_positions',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('workshop_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('rotation', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('scale', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.CheckConstraint('rotation >= 0 AND rotation < 360', name=op.f('check_rotation')),
                    sa.CheckConstraint('scale > 0', name=op.f('check_scale')),
                    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], name=op.f('asset_positions_asset_id_fkey'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.workshop_id'], name=op.f('asset_positions_workshop_id_fkey'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('asset_positions_pkey'))
                    )
    op.create_index(op.f('ix_asset_positions_workshop_id'), 'asset_positions', ['workshop_id'], unique=False)
    op.create_index(op.f('ix_asset_positions_is_active'), 'asset_positions', ['is_active'], unique=False)
    op.create_index(op.f('ix_asset_positions_id'), 'asset_positions', ['id'], unique=False)
    op.create_index(op.f('ix_asset_positions_asset_id'), 'asset_positions', ['asset_id'], unique=False)
    op.create_table('workshops',
                    sa.Column('workshop_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('background_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
                    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
                    sa.Column('workshop_width', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('workshop_height', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('offset_x', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('offset_y', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
                    sa.Column('workshop_scale', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=True),
                    sa.Column('color', sa.VARCHAR(length=20), server_default=sa.text("'#546E7A'::character varying"), autoincrement=False, nullable=True),
                    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('workshop_id', name=op.f('workshops_pkey'))
                    )
    op.create_index(op.f('ix_workshops_workshop_id'), 'workshops', ['workshop_id'], unique=False)
    op.create_index(op.f('ix_workshops_name'), 'workshops', ['name'], unique=False)
    op.create_index(op.f('ix_workshops_is_active'), 'workshops', ['is_active'], unique=False)
    op.create_index(op.f('ix_workshops_code'), 'workshops', ['code'], unique=True)
    # ### end Alembic commands ###