"""change model Position

Revision ID: 71abeb84ca81
Revises: 22e897966a6a
Create Date: 2026-07-07 12:09:53.102733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71abeb84ca81'
down_revision: Union[str, Sequence[str], None] = '22e897966a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zup_positions', 'creation_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('zup_positions', 'expiration_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zup_positions', 'expiration_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('zup_positions', 'creation_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
