"""add comment for zup_employees

Revision ID: 796e4d0ffced
Revises: cc84339cdbc2
Create Date: 2026-07-15 16:51:55.681004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '796e4d0ffced'
down_revision: Union[str, Sequence[str], None] = 'cc84339cdbc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zup_employees', sa.Column('comment', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zup_employees', 'comment')
    # ### end Alembic commands ###
