"""add model_name in assets

Revision ID: 8d3b5d2da3bc
Revises: 3c0df74d8536
Create Date: 2026-07-08 15:01:56.591326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3b5d2da3bc'
down_revision: Union[str, Sequence[str], None] = '3c0df74d8536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'asset_assignments', 'assets', ['asset_id'], ['asset_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset_assignments', type_='foreignkey')
    # ### end Alembic commands ###
