"""add temporary fields

Revision ID: 8fe2dc2a1f81
Revises: 8d3b5d2da3bc
Create Date: 2026-07-10 09:32:22.234311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe2dc2a1f81'
down_revision: Union[str, Sequence[str], None] = '8d3b5d2da3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('parent_name', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('manufacturer_name', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('vendor_name', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('os_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'os_name')
    op.drop_column('assets', 'vendor_name')
    op.drop_column('assets', 'manufacturer_name')
    op.drop_column('assets', 'parent_name')
    # ### end Alembic commands ###
