"""add type for assets

Revision ID: a48b018c15bc
Revises: add5d3b0a321
Create Date: 2026-07-08 11:19:51.480025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a48b018c15bc'
down_revision: Union[str, Sequence[str], None] = 'add5d3b0a321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_login'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.add_column('assets', sa.Column('asset_type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_assets_asset_type_id'), 'assets', ['asset_type_id'], unique=False)
    op.create_foreign_key(None, 'assets', 'asset_types', ['asset_type_id'], ['asset_type_id'])
    op.drop_constraint(op.f('zup_managers_guid_employee_fkey'), 'zup_managers', type_='foreignkey')
    op.drop_constraint(op.f('zup_managers_guid_manager_fkey'), 'zup_managers', type_='foreignkey')
    op.create_foreign_key(None, 'zup_managers', 'zup_employees', ['guid_employee'], ['guid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'zup_managers', 'zup_employees', ['guid_manager'], ['guid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zup_managers', type_='foreignkey')
    op.drop_constraint(None, 'zup_managers', type_='foreignkey')
    op.create_foreign_key(op.f('zup_managers_guid_manager_fkey'), 'zup_managers', 'zup_employees', ['guid_manager'], ['guid'])
    op.create_foreign_key(op.f('zup_managers_guid_employee_fkey'), 'zup_managers', 'zup_employees', ['guid_employee'], ['guid'])
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_asset_type_id'), table_name='assets')
    op.drop_column('assets', 'asset_type_id')
    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_sessions_pkey'))
    )
    op.create_index(op.f('ix_user_sessions_login'), 'user_sessions', ['login'], unique=True)
    # ### end Alembic commands ###
