"""remove redis and change manager.py

Revision ID: add5d3b0a321
Revises: daa4b1a133b8
Create Date: 2026-07-08 10:23:10.739312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add5d3b0a321'
down_revision: Union[str, Sequence[str], None] = 'daa4b1a133b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_login'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_constraint(op.f('zup_managers_guid_employee_fkey'), 'zup_managers', type_='foreignkey')
    op.drop_constraint(op.f('zup_managers_guid_manager_fkey'), 'zup_managers', type_='foreignkey')
    op.create_foreign_key(None, 'zup_managers', 'zup_employees', ['guid_manager'], ['guid'], ondelete='CASCADE')
    op.create_foreign_key(None, 'zup_managers', 'zup_employees', ['guid_employee'], ['guid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zup_managers', type_='foreignkey')
    op.drop_constraint(None, 'zup_managers', type_='foreignkey')
    op.create_foreign_key(op.f('zup_managers_guid_manager_fkey'), 'zup_managers', 'zup_employees', ['guid_manager'], ['guid'])
    op.create_foreign_key(op.f('zup_managers_guid_employee_fkey'), 'zup_managers', 'zup_employees', ['guid_employee'], ['guid'])
    op.create_table('user_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_sessions_pkey'))
    )
    op.create_index(op.f('ix_user_sessions_login'), 'user_sessions', ['login'], unique=True)
    # ### end Alembic commands ###
