"""change model Position

Revision ID: c922a3037e56
Revises: 633cb5ea4be7
Create Date: 2026-07-07 12:29:19.584680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c922a3037e56'
down_revision: Union[str, Sequence[str], None] = '633cb5ea4be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'zup_assignments', 'zup_positions', ['position_guid'], ['guid'])
    op.alter_column('zup_positions', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('zup_positions', 'name_en',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zup_positions', 'name_en',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('zup_positions', 'name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_constraint(None, 'zup_assignments', type_='foreignkey')
    # ### end Alembic commands ###
