"""remove asset_class

Revision ID: cac6931f5425
Revises: d2aaae146d7e
Create Date: 2026-07-08 13:42:19.704939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cac6931f5425'
down_revision: Union[str, Sequence[str], None] = 'd2aaae146d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # # 1. Копируем asset_type_id из asset_classes в asset_models
    # op.execute("""
    #            UPDATE asset_models
    #            SET asset_type_id = ac.asset_type_id
    #            FROM asset_classes ac
    #            WHERE asset_models.class_id = ac.class_id
    #            """)
    #
    # # 2. Копируем asset_type_id из asset_classes в assets
    # op.execute("""
    #            UPDATE assets
    #            SET asset_type_id = ac.asset_type_id
    #            FROM asset_classes ac
    #            WHERE assets.class_id = ac.class_id
    #            """)
    #
    # # 3. Удаляем FK constraints
    # op.drop_constraint('asset_models_class_id_fkey', 'asset_models', type_='foreignkey')
    # op.drop_constraint('assets_class_id_fkey', 'assets', type_='foreignkey')
    #
    # # 4. Удаляем колонки class_id
    # op.drop_column('asset_models', 'class_id')
    # op.drop_column('assets', 'class_id')
    #
    # # 5. Удаляем таблицу asset_classes
    # op.drop_table('asset_classes')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_classes_asset_type_id'), table_name='asset_classes')
    op.drop_index(op.f('ix_asset_classes_class_id'), table_name='asset_classes')
    op.drop_index(op.f('ix_asset_classes_class_name'), table_name='asset_classes')
    op.drop_table('asset_classes')
    op.add_column('asset_models', sa.Column('name', sa.String(length=150), nullable=False))
    op.add_column('asset_models', sa.Column('asset_type_id', sa.Integer(), nullable=True))
    op.alter_column('asset_models', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_asset_models_class_id'), table_name='asset_models')
    op.drop_index(op.f('ix_asset_models_model_name'), table_name='asset_models')
    op.create_index(op.f('ix_asset_models_asset_type_id'), 'asset_models', ['asset_type_id'], unique=False)
    op.create_index(op.f('ix_asset_models_name'), 'asset_models', ['name'], unique=False)
    op.drop_constraint(op.f('asset_models_class_id_fkey'), 'asset_models', type_='foreignkey')
    op.create_foreign_key(None, 'asset_models', 'asset_types', ['asset_type_id'], ['asset_type_id'])
    op.drop_column('asset_models', 'class_id')
    op.drop_column('asset_models', 'model_name')
    op.drop_index(op.f('ix_assets_class_id'), table_name='assets')
    op.drop_constraint(op.f('assets_class_id_fkey'), 'assets', type_='foreignkey')
    op.drop_column('assets', 'class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # op.create_table(
    #     'asset_classes',
    #     sa.Column('class_id', sa.Integer(), primary_key=True),
    #     sa.Column('class_name', sa.String(150), nullable=False),
    #     sa.Column('description', sa.Text()),
    #     sa.Column('asset_type_id', sa.Integer(), sa.ForeignKey('asset_types.asset_type_id')),
    #     sa.Column('created_by', sa.String(20)),
    #     sa.Column('updated_by', sa.String(20)),
    #     sa.Column('created_at', sa.DateTime(), nullable=False),
    #     sa.Column('updated_at', sa.DateTime()),
    # )
    # # Добавляем class_id обратно
    # op.add_column('assets', sa.Column('class_id', sa.Integer(), sa.ForeignKey('asset_classes.class_id')))
    # op.add_column('asset_models', sa.Column('class_id', sa.Integer(), sa.ForeignKey('asset_classes.class_id')))

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('assets_class_id_fkey'), 'assets', 'asset_classes', ['class_id'], ['class_id'])
    op.create_index(op.f('ix_assets_class_id'), 'assets', ['class_id'], unique=False)
    op.add_column('asset_models', sa.Column('model_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('asset_models', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'asset_models', type_='foreignkey')
    op.create_foreign_key(op.f('asset_models_class_id_fkey'), 'asset_models', 'asset_classes', ['class_id'], ['class_id'])
    op.drop_index(op.f('ix_asset_models_name'), table_name='asset_models')
    op.drop_index(op.f('ix_asset_models_asset_type_id'), table_name='asset_models')
    op.create_index(op.f('ix_asset_models_model_name'), 'asset_models', ['model_name'], unique=False)
    op.create_index(op.f('ix_asset_models_class_id'), 'asset_models', ['class_id'], unique=False)
    op.alter_column('asset_models', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('asset_models', 'asset_type_id')
    op.drop_column('asset_models', 'name')
    op.create_table('asset_classes',
    sa.Column('class_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('asset_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.asset_type_id'], name=op.f('asset_classes_asset_type_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['zup_employees.employee_id'], name=op.f('asset_classes_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['zup_employees.employee_id'], name=op.f('asset_classes_updated_by_fkey')),
    sa.PrimaryKeyConstraint('class_id', name=op.f('asset_classes_pkey'))
    )
    op.create_index(op.f('ix_asset_classes_class_name'), 'asset_classes', ['class_name'], unique=False)
    op.create_index(op.f('ix_asset_classes_class_id'), 'asset_classes', ['class_id'], unique=False)
    op.create_index(op.f('ix_asset_classes_asset_type_id'), 'asset_classes', ['asset_type_id'], unique=False)
    # ### end Alembic commands ###
