"""add active_directory_login

Revision ID: cc84339cdbc2
Revises: 8fe2dc2a1f81
Create Date: 2026-07-13 16:38:19.770503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc84339cdbc2'
down_revision: Union[str, Sequence[str], None] = '8fe2dc2a1f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zup_employees', sa.Column('active_directory_login', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_zup_employees_active_directory_login'), 'zup_employees', ['active_directory_login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zup_employees_active_directory_login'), table_name='zup_employees')
    op.drop_column('zup_employees', 'active_directory_login')
    # ### end Alembic commands ###
