"""add class_id for assets

Revision ID: d2aaae146d7e
Revises: a48b018c15bc
Create Date: 2026-07-08 12:14:22.895895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2aaae146d7e'
down_revision: Union[str, Sequence[str], None] = 'a48b018c15bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_assets_class_id'), 'assets', ['class_id'], unique=False)
    op.create_foreign_key(None, 'assets', 'asset_classes', ['class_id'], ['class_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_class_id'), table_name='assets')
    op.drop_column('assets', 'class_id')
    # ### end Alembic commands ###
