"""add every_week_check_ equipment

Revision ID: d38ff63167a6
Revises: 973bf016d2dd
Create Date: 2026-08-18 10:02:40.850847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from openpyxl.descriptors import Integer
from sqlalchemy import false

# revision identifiers, used by Alembic.
revision: str = 'd38ff63167a6'
down_revision: Union[str, Sequence[str], None] = '973bf016d2dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('every_week_check', sa.Boolean(), nullable=False, server_default=false()))
    op.add_column('assets', sa.Column('next_service', sa.Date(), nullable=True))
    op.add_column('assets', sa.Column('service_period', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'service_period')
    op.drop_column('assets', 'next_service')
    op.drop_column('assets', 'every_week_check')
    # ### end Alembic commands ###
