"""delete report and assignment

Revision ID: daa4b1a133b8
Revises: c922a3037e56
Create Date: 2026-07-08 08:37:11.539404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daa4b1a133b8'
down_revision: Union[str, Sequence[str], None] = 'c922a3037e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zup_assignments_department_guid'), table_name='zup_assignments')
    op.drop_index(op.f('ix_zup_assignments_employee_guid'), table_name='zup_assignments')
    op.drop_index(op.f('ix_zup_assignments_end_date'), table_name='zup_assignments')
    op.drop_index(op.f('ix_zup_assignments_id'), table_name='zup_assignments')
    op.drop_index(op.f('ix_zup_assignments_position_guid'), table_name='zup_assignments')
    op.drop_index(op.f('ix_zup_assignments_start_date'), table_name='zup_assignments')
    op.drop_table('zup_assignments')
    op.drop_index(op.f('ix_zup_reports_department_name'), table_name='zup_reports')
    op.drop_table('zup_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zup_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('total_employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('present_employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('absent_employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attendance_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('zup_reports_pkey'))
    )
    op.create_index(op.f('ix_zup_reports_department_name'), 'zup_reports', ['department_name'], unique=False)
    op.create_table('zup_assignments',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('employee_guid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('department_guid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('position_guid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('fte', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_guid'], ['zup_departments.guid'], name=op.f('zup_assignments_department_guid_fkey')),
    sa.ForeignKeyConstraint(['employee_guid'], ['zup_employees.guid'], name=op.f('zup_assignments_employee_guid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('zup_assignments_pkey'))
    )
    op.create_index(op.f('ix_zup_assignments_start_date'), 'zup_assignments', ['start_date'], unique=False)
    op.create_index(op.f('ix_zup_assignments_position_guid'), 'zup_assignments', ['position_guid'], unique=False)
    op.create_index(op.f('ix_zup_assignments_id'), 'zup_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_zup_assignments_end_date'), 'zup_assignments', ['end_date'], unique=False)
    op.create_index(op.f('ix_zup_assignments_employee_guid'), 'zup_assignments', ['employee_guid'], unique=False)
    op.create_index(op.f('ix_zup_assignments_department_guid'), 'zup_assignments', ['department_guid'], unique=False)
    # ### end Alembic commands ###
